#/*
# * Copyright {c} 2020-2021, SERI Development Team
# *
# * SPDX-License-Identifier: Apache-2.0
# *
# * Change Logs:
# * Date         Author          Notes
# * 2022-03-27   Lyons           first version
# */

TARGET          = m3

Q               = @

PROJPATH        = ../..
WORKPATH        = .

include ../config.mk

CFILES0         = ${WORKPATH}/main0.c
CFILES1         = ${WORKPATH}/main1.c

include ../build.mk
